controllers:
   - name: 'dwa'
     type: 'dwa_local_planner/DWAPlannerROS'
   - name: 'trajectory_planner'
     type: 'base_local_planner/TrajectoryPlannerROS'
   - name: 'teb'
     type: 'teb_local_planner/TebLocalPlannerROS'  
      
dwa: 
  max_vel_trans: 1.5
  max_vel_x: 1.5
  min_vel_x: -1.5
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 1.0
  min_vel_theta: 0.1
  acc_lim_x: 3.0

  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 0.5

  latch_xy_goal_tolerance: true
  acc_lim_trans: 2.0
  prune_plan: false  # true yields to robot stopping every second
  vx_samples: 10
  vy_samples: 0
  
  #time needed to stop the robot.
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.5 # add more here?
  path_distance_bias: 5.0 #default 32.0
  occdist_scale: 0.85 #default 0.01

trajectory_planner:
  meter_scoring: true
  
  # Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_theta:  0.45
  max_vel_x: 0.55
  min_vel_x: -0.15
  max_vel_theta: 0.45
  min_obstacle_height: -2.0
  max_obstacle_height: 5.0
  min_vel_theta: 0.1
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  path_distance_bias: 0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  goal_distance_bias: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

teb:
  # odom_topic: odom
  # map_frame: map
    
  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: false
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 0
  allow_init_with_backwards_motion: true
    
  # Robot  
  max_vel_x: 1.5
  max_vel_x_backwards: 0.3 # Zero value results in robot getting stuck a lot
  max_vel_theta: 1.0
  acc_lim_x: 1.3
  acc_lim_theta: 0.7
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    radius: 0.4 # for type "circular"
    line_start: [-0.40, 0.0] # for type "line"
    line_end: [0.40, 0.0] # for type "line"
    front_offset: 0.2 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.2 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [ [-0.40, 0.25], [0.45, 0.25], [0.45, -0.25], [-0.40, -0.25] ] # for type "polygon"

  # GoalTolerance
  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.5
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.36
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: False
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet

  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 3
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
  selection_prefer_initial_plan: 0.95
  
  # recovery
  shrink_horizon_backup: false
  oscillation_recovery: false
 