transform_tolerance: 2.5
max_obstacle_range: 30.0
min_obstacle_height: 0.0
max_obstacle_height: 5.0

plugins:
  - { name: "obstacle_layer", type: "costmap_2d::ObstacleLayer"}
  - { name: "inflation_layer", type: "costmap_2d::InflationLayer" }

obstacle_layer:
  enabled: true
  footprint_clearing_enable: false
  track_unknown_space: true
  obstacle_range: 30.0
  raytrace_range: 30.0
  observation_sources: laser_front laser_rear

  laser_front:
    {
      topic: laser_front,
      data_type: LaserScan,
      expected_update_rate: 1.0,
      marking: true,
      clearing: true,
      max_obstacle_height: 3.0,
      min_obstacle_height: 0.0,
      obstacle_range: 30.0,
      raytrace_range: 30.0,
      inf_is_valid: true,
    }

  laser_rear:
    {
      topic: laser_rear,
      data_type: LaserScan,
      expected_update_rate: 1.0,
      marking: true,
      clearing: true,
      max_obstacle_height: 3.0,
      min_obstacle_height: 0.0,
      obstacle_range: 30.0,
      raytrace_range: 30.0,
      inf_is_valid: true,
    }
