planners:
  - name: 'GlobalPlanner'
    type: 'global_planner/GlobalPlanner'
  - name: 'navfn'
    type: 'navfn/NavfnROS'      
    
planner_frequency: 5.0
planner_patience: 5.0
planner_max_retries: 2

controller_frequency: 5.0
controller_patience: 5.0

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behaviour: false
  lethal_cost: 255
  neutral_cost: 66
  cost_factor: 0.55
  
navfn:
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: true